Feature/menu page
CoffeeBy2024/server pull request #1
Opened 2024-08-13 15:44 UTC by timosheyka

- [x] **WorkingHour Module:** 
 - refactored
 - added error handling
 - POST/PATCH method reworked
- [x]  **Category Module:**
 - methods allowed: GET, GET(':id'), POST
 - relationship with ShopCategory implemented
- [x] **ShopCategory Module:**
 - no REST API method allowed, features normalisation
 - relationship with Category, Shop, Product implemented
- [x] **Product Module:**
 - methods allowed: GET('shop/:sid/product/:pid'), GET('shop/:id/products/'), POST('shop/:id/product'), PATCH/DELETE('shop/:sid/product/:id')
 - relationship with ShopCategory implemented
- [x] **Shop Module:**
 - added relationship with ShopCategory

2024-09-05 10:36 UTC, timosheyka commented
### Unit and Integration Tests
* **Completed Tests for:**
  - Validators: [Military Time]
  - Modules: [Category, Product, Shop, Shop Category, Working Hours]
 
 * **Each Validator Testing involves:**
   - Appropriate Reaction for Correct / Incorrect Input
 * **Each Module Testing involves:**
   - DTOs Tests
   - Controller Tests
   - Service Tests
   
  * **Final Result - bunch of bug fixes resulting in 100% code coverage**

2024-09-21 15:49 UTC, mxgvrl commented on src/modules/category/category.service.ts
> +    switch (category) {
Avoid manual switch switches and use TypeScript's built-in methods to look up values in enum. 
`  
convertToEnum(category: string): CATEGORY {
    const categoryValue = CATEGORY[category as keyof typeof CATEGORY];

    if (!categoryValue) {
      throw new NotFoundException(`Category with name ${category} not found`);
    }

    return categoryValue;
  }`

2024-09-21 15:53 UTC, mxgvrl commented on src/modules/category/category.service.ts
> +    const categoryName = CATEGORY[this.convertToEnum(name)];
`const categoryName = this.convertToEnum(name);`

2024-09-21 15:57 UTC, mxgvrl commented on src/modules/category/entities/category.entity.ts
> +export enum CATEGORY {
If this enum is used exclusively in a given class (Category), storing it in the same file as that class may be justified. This improves data locality - all information about the category is collected in one place.

If CATEGORY is used in different places in the project (for example, in other entities, services, or DTOs), it is better to put it in a separate file. This makes the code more modular and easier to maintain.

2024-09-21 16:49 UTC, mxgvrl commented
@timosheyka 

Recommendations:
1. Pay attention on code readability. If your code satisfies your eye, it doesn't mean it readable and understandable for your teammate, which is much more important
2. Try to make your code maintainable 
3. Follow the same style and technics in every place possible
4. Avoid making unnecessary calls to the DB. It slows down your app the most
5. Use NestJS/TS constructions instead of trying to invent your own. You don't need to recreate what already done
6. Specify return type where needed
7. Keep it as simple as possible

Review comments applicable all across the branch.
Take your time for refactoring and optimization.

2024-09-23 15:42 UTC, mxgvrl requested changes

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/category/entities/category.entity.ts
> +}
```
export enum CATEGORY {
  coffee = 'coffee',
  bakery = 'bakery',
  drinks = 'drinks',
  odds = 'odds',
}
```

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/shop/shop/shop.controller.ts
> +    if (name && category) throw new Error('Too Many Parametrs Entered');
Instead of throwing a regular error, it is better to use special error classes like BadRequestException from NestJS to handle API errors correctly

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/shop/shop/shop.controller.ts
> +    @Query('name') name?: string
If both parameters are optional, it is logical to make sure that at least one of them is passed, otherwise return all records

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/shop/shop/shop.controller.ts
> +    return await Promise.all(
Unreadable

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/shop/shop/shop.controller.ts
> +  @Get()
```
@Get()
@ApiQuery({
  name: 'category',
  required: false,
  type: 'string',
  description: 'Category of the shop',
})
@ApiQuery({
  name: 'name',
  required: false,
  type: 'string',
  description: 'Name of the shop',
})
async getCategorySelection(
  @Query('category') category?: string,
  @Query('name') name?: string,
) {
  // both category and name specified 
  if (name && category) {
    throw new BadRequestException('Too many parameters entered. Provide either name or category, not both.');
  }

  // only name specified
  if (name) {
    return this.shopService.findByName(name);
  }

  // If no name or category is specified, return all records
  if (!category) {
    return this.shopService.findAll();
  }

  // if category passed only
  const categoryEntity = await this.categoryService.findOneByName(category);

  // looking for shops by category
  const shopsByCategory = await this.shopCategoryService.findAllByName(categoryEntity);

  // return shops
  return Promise.all(shopsByCategory.map((shop) => this.shopService.findOne(shop.shop.id)));
}
```

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/product/product.controller.ts
> +  @Post('shop/:id/product')
if you decided to use Swagger annotations – use it in every controller

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/product/product.controller.ts
> +  @Post('shop/:id/product')
1. Instead of manually calling methods to handle missing data, such as this.shopService.handleNonExistingShop, you can use exceptions and a global error handler to simplify the logic.
2. To make the code cleaner, asynchronous operations that are independent of each other can be executed in parallel.
3. Explicitly specifying types for input parameters and return value will improve code readability and maintainability.
4. Checking for shop availability and creating a shop category can be optimised to reduce the number of database accesses.

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/product/product.controller.ts
> +  @Post('shop/:id/product')
```
@Post('shop/:id/product')
async create(
  @Param('id') id: number,
  @Query('category') categoryName: string,
  @Body() createProductDto: CreateProductDto
): Promise<Product> {
  const category = await this.categoryService.findOneByName(categoryName);
  if (!category) {
    throw new NotFoundException(`Category with name ${categoryName} not found`);
  }

  let shopCategory = await this.shopCategoryService.findOneByName(id, category);

  if (!shopCategory) {
    const shop = await this.shopService.findOne(id);
    
    if (!shop) {
      throw new NotFoundException(`Shop with id ${id} not found`);
    }

    shopCategory = await this.shopCategoryService.create({ shop, category });
  }

  return this.productService.create(createProductDto, shopCategory);
}
```

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/product/product.controller.ts
> +  @Get('shop/:id/products/')
Same here

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/product/product.controller.ts
> +  @Get('shop/:id/products/')
```
@Get('shop/:id/products/')
@ApiQuery({
  name: 'category',
  required: false,
  type: 'string',
  explode: false,
})
async getCategorySelection(
  @Param('id') shop_id: number,
  @Query('category') category?: string
) {
  if (!category) {
    return this.productService.findAll();
  }

  const [categoryEntity, shopCategory] = await Promise.all([
    this.categoryService.findOneByName(category),
    this.shopCategoryService.findOneById(shop_id)
  ]);

  if (!categoryEntity) {
    throw new NotFoundException(`Category with name ${category} not found`);
  }

  if (!shopCategory) {
    throw new NotFoundException(`Shop with id ${shop_id} not found`);
  }

  return this.productService.findAllByCategory(shopCategory.id);
}
```

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/product/product.controller.ts
> +    return !category
Unreadable code

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/shop/working_hours/working_hours.controller.ts
> +    await this.shopService.createWorkingHours(shop);
A call to this.shopService.createWorkingHours(shop) can be combined with the creation of working hours via workingHoursService to avoid unnecessary calls.

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/shop/working_hours/working_hours.controller.ts
> +import { Body, Controller, Get, Param, Patch, Post } from '@nestjs/common';
```
  @Post(':id/working_hours')
  async createWorkingHours(
    @Param('id') id: number,
    @Body() createWorkingHoursDto: CreateWorkingHoursDto
  ): Promise<WorkingHours> {
    const shop = await this.shopService.findOne(id);
    if (!shop) {
      throw new NotFoundException(`Shop with id ${id} not found`);
    }

    const workingHours = await this.workingHoursService.create({
      ...createWorkingHoursDto,
      shop,
    });

    return this.workingHoursService.ensureWH(workingHours);
  }

  @Get(':id/working_hours')
  findWHByShop(@Param('id') id: number): Promise<WorkingHours[]> {
    return this.workingHoursService.findAllById(id);
  }

  @Patch(':id/working_hours')
  async updateWorkingHours(
    @Param('id') id: number,
    @Body() updateWorkingHoursDto: UpdateWorkingHoursDto
  ): Promise<WorkingHours> {
    const shop = await this.shopService.findOne(id);
    if (!shop) {
      throw new NotFoundException(`Shop with id ${id} not found`);
    }

    return this.workingHoursService.update(id, updateWorkingHoursDto);
  }
}
```

2024-09-23 15:42 UTC, mxgvrl commented on src/modules/category/category.service.ts
> +    switch (category) {
@timosheyka

2024-09-23 16:19 UTC, miwiwiq commented on src/modules/product/product.controller.ts
> +  @Delete('shop/:sid/product/:id')
`'shop/:sid/product/` - noticed this nesting in every endpoint, please consider moving this to the @Controller annotation to avoid repeating.

2024-09-23 16:26 UTC, miwiwiq commented on src/modules/product/product.service.ts
> +    return await this.productRepository.save(
do we need to await here?

2024-09-23 16:39 UTC, miwiwiq commented on src/modules/product/product.service.ts
> +    const product = await this.productRepository.delete({ id: id });
```suggestion
    const product = await this.productRepository.delete({ id });
```

2024-09-23 16:48 UTC, miwiwiq commented on src/modules/product/product.service.ts
> +    return product.affected && product.affected > 0;
do we care about the result of this function call? if we do, then we can simplify it to `return !!product.affected` - if its 0 or null we return false, otherwise - true, but I would just go with throwing that delete request and that's it, without awaiting for its execution result, if any error happens during the execution we will catch and log that anyways at upper level.

2024-09-23 16:51 UTC, miwiwiq commented on src/modules/shop/shop-category/shop-category.service.ts
> +  async findAllByName(category: Category) {
why is it findAllByName if we search by category?

misleading name

2024-09-23 16:56 UTC, miwiwiq commented on src/modules/shop/shop-category/shop-category.service.ts
> +}
is there a reason for this function to be extracted? its just a small catch block and was reused only once if I am not mistaken

you probably want to reuse it in both findOneById and findOneByName functions or remove at all.

2024-09-23 17:00 UTC, miwiwiq commented on src/modules/shop/shop-category/shop-category.service.ts
> +}
Also I wonder if this function can be much improved in the future, for example can we really use this function to wrap any function in the shop category service? Looks hard for extension, consider making in more generic if it worth the effort 😅

2024-09-23 17:04 UTC, miwiwiq commented on src/modules/shop/shop/shop.service.ts
> +    return await this.shopRepository.findOneBy({ id: id });
```suggestion
    return await this.shopRepository.findOneBy({ id });
```

2024-09-23 17:04 UTC, miwiwiq commented on src/modules/shop/shop/shop.service.ts
> +    return await this.shopRepository.find({ where: { name: name } });
```suggestion
    return await this.shopRepository.find({ where: { name } });
```

2024-09-24 16:56 UTC, miwiwiq commented on src/modules/category/category.controller.ts
> +@Controller('category')
https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design#organize-the-api-design-around-resources

Its considered a good practice to keep resource names plural, I noticed there was some inconsistency in naming, please consider reviewing names and keep them simple and adhering to one style

```
e.g.
@Controller('categories')
export class CategoryController
@Post()
createCategory(@Body() createCategoryDto: CreateCategoryDto) // -> POST /api/categories
@Get()
createCategory(@Body() createCategoryDto: CreateCategoryDto) // -> GET /api/categories (get all)
@Get(':category')
createCategory(@Body() createCategoryDto: CreateCategoryDto) // -> GET /api/categories/:categoryName (get one by name)
```

2024-09-24 16:56 UTC, miwiwiq commented on src/modules/product/product.controller.ts
> +@Controller('shop')
If we really need to keep nesting ('/shops/:shop_id/products/:id') can we extract the whole '/shops/:sid/products/' part to the controller and only pass product id as a param to these endpoints down below where needed?

Anyways I would probably also suggest to completely split apart products and shops because they doesn't seem to be bound (at least yet) and make the API slightly less predictable.
```
GET/POST/PUT/DELETE /shops/[:id] (all shop-related manipulations inside the ShopController)
GET/POST/PUT/DELETE /products/[:id] (all product-related manipulations inside the ProductController)
```

Also please note the consistency across endpoint names ('/products'/ only, not '/product' and '/products').

2024-09-24 16:56 UTC, miwiwiq commented on src/modules/product/product.controller.ts
> +  })
Not sure here, judging only from the description, but api doc says its `Category of the shop`, should it be in the productController?

2024-09-24 16:56 UTC, miwiwiq commented on src/modules/shop/shop/shop.controller.ts
> +    );
```suggestion
    return Promise.all(
      shopsByCategory.map(({ shop }) => this.shopService.findOne(shop.id))
    );
```

2024-09-24 16:56 UTC, miwiwiq commented on src/modules/shop/shop/shop.service.ts
> +    return !!(await this.shopRepository.delete({ id })).affected;
Its not critical here but I noticed that quick a few times in this PR so worth mentioning. 

Let's try to avoid unnecessary call nesting, I mean its cool to save a few, but extra code lines are free, please consider relying on descriptive names rather than saving them extra 1-2 lines of code. For example:
```suggestion
    const deleteResult = await this.shopRepository.delete({ id });
    return !!deleteResult.affected;
```

2024-10-01 10:44 UTC, merged